name: Deno CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno task lint

      - name: Run tests
        run: deno task test
        env:
          # Use GITHUB_TOKEN with minimal scope for tests
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
