name: GitHub Token Rotation Reminder

on:
  # Run on the 1st of every month
  schedule:
    - cron: "0 0 1 * *"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  token-rotation-reminder:
    runs-on: ubuntu-latest
    name: Remind to rotate GitHub token

    steps:
      - name: Check token expiration
        id: check-token
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get current date and calculate 90 days from now (typical token rotation period)
            const today = new Date();
            const rotationDate = new Date(today);
            rotationDate.setDate(rotationDate.getDate() + 90);

            // Format dates for display
            const formattedToday = today.toISOString().split('T')[0];
            const formattedRotation = rotationDate.toISOString().split('T')[0];

            // Store these in outputs
            core.setOutput('today', formattedToday);
            core.setOutput('rotation_date', formattedRotation);

      - name: Create token rotation issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const today = '${{ steps.check-token.outputs.today }}';
            const rotationDate = '${{ steps.check-token.outputs.rotation_date }}';

            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `⚠️ Security: Rotate GitHub Token by ${rotationDate}`,
              body: `## GitHub Token Rotation Reminder

            As part of security best practices, please rotate the \`STAR_MANAGEMENT_TOKEN\` secret used for GitHub star management workflows.

            ### Action Required

            1. Generate a new GitHub personal access token with the minimum required permissions:
               - \`repo\` (to access your starred repositories)
               - \`user:read\` (to read star information)

            2. Go to your repository settings → Secrets and variables → Actions

            3. Update the \`STAR_MANAGEMENT_TOKEN\` secret with the new token value

            4. Verify that workflows continue to function as expected

            ### Security Notes

            - Never commit tokens to the repository
            - Use the minimum permissions necessary
            - Set an expiration date on your token (recommended: 90 days)
            - Document the token's purpose and permissions in your internal records

            **Reminder date:** ${today}
            **Recommended rotation by:** ${rotationDate}

            *This is an automated reminder generated by the token-rotation workflow.*`,
              labels: ['security', 'maintenance']
            });

            console.log(`Created token rotation reminder issue #${issue.data.number}`);
